baseurl               = "https://calebeverett.io"
languageCode          = "en-us"
title                 = "Caleb Everett"
theme                 = "resume-mdl"
pluralizelisttitles   = false   # http://pygments.org/docs/formatters/#HtmlFormatter
pygmentsuseclasses    = true
pygmentsstyle         = "manni" #['algol', 'algol_nu', 'autumn', 'borland', 'bw', 'colorful', 'default', 'emacs', 'friendly', 'fruity', 'igor', 'lovelace', 'manni', 'monokai', 'murphy', 'native', 'paraiso-dark', 'paraiso-light', 'pastie', 'perldoc', 'rrt', 'tango', 'trac', 'vim', 'vs', 'xcode']
PymentsCodeFences     = true

[taxonomies]
tag                   = "tags"

[[menu.main]]
name                  = "Home"
pre                   = "home"
url                   = "/"
weight                = 10
[[menu.main]]
name                  = "Posts"
pre                   = "subject"
url                   = "/posts"
weight                = 20
[[menu.main]]
name                  = "Resume"
pre                   = "work"
url                   = "/resume"
weight                = 30


[params]
avatar                = "avatar.jpg"
default_featured_img  = "/images/default_featured_img.png"
google_analytics_id   = "UA-80388935-2"
email                 = "mail@calebeverett.io"
welcome = """
I'm looking for an opportunity to develop cutting edge applications that solve complex problems in a hands-on capacity that leverages my deep financial expertise, exceptional analytical capabilities and strong and rapidly growing technical skills.

##### Highlights
* Studied quantitative marketing research at The Wharton School of the University of Pennsylvania
* Top tier analyst in the Mergers and Acquisitions department at Morgan Stanley
* First outside third-year analyst hired into Blackstone's Corporate Principal Group
* Promoted from Associate to Partner in three years at FFL Partners
* Built a vocational school from the ground up with over 80% completion and job placement rates
* Learned how to developed applications using Python, Data Science and Machine Learning, Node.js, Javascript, HTML, CSS, Linux, LXD, Docker and Amazon Web Services through self-directed learning and online courses
"""

[params.org_types]
10                    = "Experience"
20                    = "Education"
30                    = "Boards"

[params.social]
# Key corresponds to css icon class name.
# Include username in first element to display.
# Add networks with new rows and updating fonts and stylesheet from https://icomoon.io/app/#/select.
facebook              = ["", "https://facebook.com/"]
github                = ["CalebEverett", "https://github.com/"]
googleplus            = ["", "https://plus.google.com/+"]
linkedin              = ["CalebEverett", "https://www.linkedin.com/in/"]
twitter               = ["", "https://twitter.com/"]

[params.share]
facebook              = true
googleplus            = true
hackernews            = true
linkedin              = true
reddit                = true
twitter               = true

[params.styles]
# Primary and accent colors will update cdn style sheet and take color inputs from here: ttps://getmdl.io/customize/index.html.
# Other colors come from here: https://material.google.com/style/color.html#color-color-palette.
# Class names can be found here: https://github.com/WebRTL/material-design-lite-rtl/blob/master/src/palette/_palette.scss.
# Use the "mdl-color-text" classes for the "_text" variables.
primary_color         = "blue_grey"
accent_color          = "indigo"
background_color      = "mdl-color--grey-50"
header_color          = ""
header_color_text     = ""
nav_header_color      = ""
nav_header_color_text = "mdl-color-text--grey-700"
nav_color             = ""
nav_color_text        = "mdl-color-text--grey-600"
chip_color            = ""
chip_color_text       = "mdl-color-text--grey-600"
home_avatar_color     = "mdl-color--white"


