baseurl            = "http://calebeverett.dev/"
languageCode       = "en-us"
title              = "Caleb Everett"
theme              = "resume-mdl"

[taxonomies]
tag                = "tags"
skill              = "skills"

[menu]
  [[menu.main]]
    name           = "Home"
    pre            = "home"
    url            = "/"
	weight         = 10
  [[menu.main]]
    name           = "Resume"
    pre            = "work"
    url            = "/resume"
	weight         = 20
  [[menu.main]]
    name           = "Projects"
    pre            = "build"
    url            = "/projects"
	weight         = 30
  [[menu.main]]
    name           = "Posts"
    pre            = "subject"
    url            = "/posts"
	weight         = 40

[params.org_types]
"10"               = "Experience"
"20"               = "Education"
"30"               = "Other"

[[params.orgs]]
	id             = "ccc"
	name           = "Career College of California"
	org_type       = "10"
	location       = "Santa Ana, CA"
	start_date     = "2010-02-01"
	end_date       = "2016-03-31"
	description    = """

	"""

[[params.orgs]]
	id             = "eme"
	name           = "Eyemart Express, Ltd."
	org_type       = "10"
	location       = "Dallas, CA"
	start_date     = "2015-02-01"
	end_date       = "2015-06-31"
	description    = """

	"""

[[params.orgs]]
	id             = "cse"
	name           = "CSE Capital, LLC"
	org_type       = "10"
	location       = "San Francisco, CA"
	start_date     = "2010-02-01"
	end_date       = "2007-01-01"
	description    = """

	"""

[[params.orgs]]
	id             = "ffl"
	name           = "Friedman, Fleischer & Lowe, LLC"
	org_type       = "10"
	location       = "San Francisco, CA"
	start_date     = "1999-01-01"
	end_date       = "2005-09-30"
	description    = """

	"""

[[params.orgs]]
	id             = "tbg"
	name           = "The Blackstone Group, L.P."
	org_type       = "10"
	location       = "New York, NY"
	start_date     = "1997-09-01"
	end_date       = "1999-08-31"
	description    = """

	"""

