baseurl            = "http://calebeverett.dev/"
languageCode       = "en-us"
title              = "Caleb Everett"
theme              = "resume-mdl"

[taxonomies]
	tag            = "tags"
	skill          = "skills"

[[menu.main]]
	name           = "Home"
	pre            = "home"
	url            = "/"
	weight         = 10
[[menu.main]]
	name           = "Resume"
	pre            = "work"
	url            = "/resume"
	weight         = 20
[[menu.main]]
	name           = "Projects"
	pre            = "build"
	url            = "/projects"
	weight         = 30
[[menu.main]]
	name           = "Posts"
	pre            = "subject"
	url            = "/posts"
	weight         = 40

[params]
	email = "caleb@calebeverett.io"

[params.org_types]
	10             = "Experience"
	20             = "Education"
	30             = "Other"

