baseurl               = "https://calebeverett.io"
languageCode          = "en-us"
title                 = "Caleb Everett"
theme                 = "resume-mdl"
pluralizelisttitles   = false   # http://pygments.org/docs/formatters/#HtmlFormatter
pygmentsuseclasses    = true
pygmentsstyle         = "manni" #['algol', 'algol_nu', 'autumn', 'borland', 'bw', 'colorful', 'default', 'emacs', 'friendly', 'fruity', 'igor', 'lovelace', 'manni', 'monokai', 'murphy', 'native', 'paraiso-dark', 'paraiso-light', 'pastie', 'perldoc', 'rrt', 'tango', 'trac', 'vim', 'vs', 'xcode']
PymentsCodeFences     = true
disqusShortname       = "CalebEverett"

[taxonomies]
tag                   = "tags"

[[menu.main]]
name                  = "Home"
pre                   = "home"
url                   = "/"
weight                = 10
[[menu.main]]
name                  = "Posts"
pre                   = "subject"
url                   = "/posts"
weight                = 20
# [[menu.main]]
# name                  = "Resume"
# pre                   = "work"
# url                   = "/resume"
# weight                = 30


[params]
avatar                = "avatar.png"
default_featured_img  = "/images/default_featured_img.png"
google_analytics_id   = "UA-80388935-2"
email                 = "caleb@calebeverett.io"
welcome = """
##### Welcome
Hello and thanks for visiting. I put this site together to have a more formal and public place to share some of the things I’ve done, I’m working on, thinking about and interested in. Putting things out there publicly forces me to put more thought into them and serves as a catalyst for connecting with people that would be fun to connect with, that can help me achieve my goals, or who would benefit from my help.

My plan is to include a wide range of content, from snippets and how-to's from coding projects, to projects I'm working on and have completed to perhaps even the ocassional thought on current issues. I'm going to try to strike the right balance between putting enough time and thought in to express myself clearly and hopefully serve as content valuable to someone other than me on the one hand, but not be such a perfectionist that it prevents me from actually getting anything out there, on the other hand.

I love being on a mission, whether to learn something new, solve a complex problem, build something beautiful or be out in the world adventuring. I love working with similarly minded folks, who are first and foremost interested in doing great work and relish the opportunity to go the extra mile in pusuit of greatness. I am not motivated by profit as a goal unto itself, but do believe that doing truly great work in the world is rewarded with uncommon financial success.

##### Interests
I am currently working on getting engaged in my next big work mission. Here are some of the things I’m thinking about doing:

* **Dig deep on deep learning** Become expert in solving deep learning problems. Learn the fast.ai software and Pytorch really well. Score highly in several Kaggle competitions. Get to know people who are in deep learning to get connected to an opportunity where I can dive deep in solving cutting edge, complex deep learning problems.
* **accomplish.ai** Research and develop a plan to develop a deep learning, block chain, gig economy, fomo application that helps lower income students with barriers to success complete online education programs.
* **Explore other potential ai applications**
    - Insurance claims processing
* **Dig deep into deep learning for finance**
    - Cross between ai and private equity
    - Learn how to develop trading algorithms
"""

[params.org_types]
10                    = "Experience"
20                    = "Education"
30                    = "Boards"

[params.social]
# Key corresponds to css icon class name.
# Include username in first element to display.
# Add networks with new rows and updating fonts and stylesheet from https://icomoon.io/app/#/select.
facebook              = ["", "https://facebook.com/"]
github                = ["CalebEverett", "https://github.com/"]
googleplus            = ["", "https://plus.google.com/+"]
linkedin              = ["CalebEverett", "https://www.linkedin.com/in/"]
twitter               = ["", "https://twitter.com/"]

[params.share]
facebook              = true
googleplus            = true
hackernews            = true
linkedin              = true
reddit                = true
twitter               = true

[params.styles]
# Primary and accent colors will update cdn style sheet and take color inputs from here: ttps://getmdl.io/customize/index.html.
# Other colors come from here: https://material.google.com/style/color.html#color-color-palette.
# Class names can be found here: https://github.com/WebRTL/material-design-lite-rtl/blob/master/src/palette/_palette.scss.
# Use the "mdl-color-text" classes for the "_text" variables.
primary_color         = "blue_grey"
accent_color          = "indigo"
background_color      = "mdl-color--grey-50"
header_color          = ""
header_color_text     = ""
nav_header_color      = ""
nav_header_color_text = "mdl-color-text--grey-700"
nav_color             = ""
nav_color_text        = "mdl-color-text--grey-600"
chip_color            = ""
chip_color_text       = "mdl-color-text--grey-600"
home_avatar_color     = "mdl-color--white"


