# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Resume mdl"
license = "MIT"
licenselink = "https://github.com/CalebEverett/resume-mdl/blob/master/LICENSE.md"
description = "A mobile first material design blog and resume theme"
homepage = "http://CalebEverett.github.io/resume-mdl"
tags = ["blog", "resume", "material design"]
features = ["blog", "resume", "responsive"]
min_version = 0.15

[author]
  name = "Caleb Everett"
  homepage = "https://calebeverett.io"

